#!/bin/bash

# Written by: Erik Uunila [https://github.com/eriku]
# Completely free to use but feel free to send me a couple of bucks
# https://cash.me/$eriku

# Check for Homebrew,
# Install if we don't have it
if test ! $(which brew); then
	echo "Installing homebrew..."
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	# Check if Command Line Tools has been installed
	if test ! $(xcode-select -p); then
		xcode-select --install
	fi
	brew update
fi

brew tap homebrew/dupes