#!/bin/bash

# Written by: Erik Uunila [https://github.com/eriku]
# Completely free to use but feel free to send me a couple of bucks
# https://cash.me/$eriku

# Gulp : http://gulpjs.com/
npm install --global gulp-cli

# Grunt : http://gruntjs.com/
npm install -g grunt-cli