#!/bin/sh 

# Written by: Erik Uunila [https://github.com/eriku]
# Completely free to use but feel free to send me a couple of bucks
# https://cash.me/$eriku

cd $1
/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ./
exit